"""Configure Gmail privately while preserving other .env settings."""
import getpass
import argparse
import re
import subprocess
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--email', help='Prefill the Gmail sender address.')
    parser.add_argument('--test', action='store_true', help='Send a delivery test after saving.')
    args = parser.parse_args()
    print('Enable Google 2-Step Verification and create an App Password:')
    print('https://myaccount.google.com/apppasswords')
    print('Enter the App Password here, never in chat. Do not use your normal password.')
    email = args.email or input('Sender Gmail address [adarsh22saji@gmail.com]: ').strip() or 'adarsh22saji@gmail.com'
    password = getpass.getpass('16-character Gmail App Password (hidden): ').replace(' ', '').strip()
    if not re.fullmatch(r'[^\s@]+@gmail\.com', email, re.I):
        raise SystemExit('Enter a valid Gmail address.')
    if not re.fullmatch(r'[A-Za-z]{16}', password):
        raise SystemExit('Enter the 16-letter App Password generated by Google.')
    path = Path(__file__).resolve().parent / '.env'
    lines = path.read_text(encoding='utf-8').splitlines() if path.exists() else []
    replacements = {'EMAIL_HOST_USER': email, 'EMAIL_HOST_PASSWORD': password,
                    'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
                    'DEFAULT_FROM_EMAIL': f'AssentTag <{email}>'}
    retained = [line for line in lines if line.partition('=')[0].strip() not in replacements]
    retained.extend(f'{key}={value}' for key, value in replacements.items())
    path.write_text('\n'.join(retained) + '\n', encoding='utf-8')
    print('Saved in .env (excluded from Git). Delivery has not been tested yet.')
    print('Restart Django, then run: python manage.py check_email --send-to ' + email)
    if args.test:
        result = subprocess.run([sys.executable, str(path.parent / 'manage.py'),
                                 'check_email', '--send-to', email], cwd=path.parent)
        if result.returncode:
            print('Delivery was not confirmed. Correct the App Password and run setup again.')
        else:
            print('Test email accepted. Return to Codex so the running app can reload these settings.')


if __name__ == '__main__':
    main()
