"""Configure Gmail privately while preserving other .env settings."""
import getpass
import argparse
import re
import subprocess
import sys
from pathlib import Path


def save_configuration(email, password):
    email = email.strip()
    password = password.replace(' ', '').strip()
    if not re.fullmatch(r'[^\s@]+@gmail\.com', email, re.I):
        raise ValueError('Enter a valid Gmail address.')
    if not re.fullmatch(r'[A-Za-z]{16}', password):
        raise ValueError('Enter the 16-letter App Password generated by Google.')
    path = Path(__file__).resolve().parent / '.env'
    lines = path.read_text(encoding='utf-8').splitlines() if path.exists() else []
    replacements = {'EMAIL_HOST_USER': email, 'EMAIL_HOST_PASSWORD': password,
                    'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
                    'DEFAULT_FROM_EMAIL': f'AssentTag <{email}>'}
    retained = [line for line in lines if line.partition('=')[0].strip() not in replacements]
    retained.extend(f'{key}={value}' for key, value in replacements.items())
    path.write_text('\n'.join(retained) + '\n', encoding='utf-8')
    return path


def open_setup_window(email):
    import tkinter as tk
    from tkinter import ttk
    import threading
    import queue
    results = queue.Queue()
    window = tk.Tk()
    window.title('AssentTag — one-time Gmail setup')
    window.geometry('570x350')
    window.resizable(False, False)
    panel = ttk.Frame(window, padding=24)
    panel.pack(fill='both', expand=True)
    ttk.Label(panel, text='Automatic OTP delivery', font=('Segoe UI',18,'bold')).pack(anchor='w')
    ttk.Label(panel, wraplength=510, text='Do this once. Afterwards the app emails a fresh OTP automatically on each request. Each OTP is valid for five minutes.').pack(anchor='w',pady=(8,16))
    ttk.Label(panel,text='Sender Gmail').pack(anchor='w')
    sender = ttk.Entry(panel,width=60); sender.insert(0,email);sender.pack(fill='x',pady=(4,10))
    ttk.Label(panel,text='Google App Password (16 letters, from the Google Create button)').pack(anchor='w')
    password = ttk.Entry(panel,show='*',width=60);password.pack(fill='x',pady=(4,12))
    status = tk.StringVar(value='Your password stays on this computer and is excluded from GitHub.')
    def deliver(address):
        try:
            python = str(Path(sys.executable).with_name('python.exe'))
            result = subprocess.run([python,str(Path(__file__).with_name('manage.py')),'check_email','--send-to',address],
                                    cwd=Path(__file__).parent,capture_output=True,timeout=90,
                                    creationflags=getattr(subprocess,'CREATE_NO_WINDOW',0))
            results.put(result.returncode == 0)
        except Exception:
            results.put(False)
    def submit():
        address=sender.get().strip()
        try:
            save_configuration(address,password.get())
        except (ValueError,OSError) as error:
            status.set(str(error) if isinstance(error,ValueError) else 'Could not save local configuration.')
            return
        password.delete(0,'end'); button.state(['disabled'])
        status.set('Saved privately. Sending the test email…')
        threading.Thread(target=deliver,args=(address,),daemon=True).start()
    def poll():
        try:
            sent=results.get_nowait()
            status.set('Test email accepted. Check Gmail, then return to Codex to reload the app.' if sent else 'Test failed. Check your Google App Password and try again.')
            button.state(['!disabled'])
        except queue.Empty:
            pass
        window.after(250,poll)
    button=ttk.Button(panel,text='Save privately & send test email',command=submit);button.pack(anchor='w')
    ttk.Label(panel,textvariable=status,wraplength=510).pack(anchor='w',pady=12)
    password.focus_set();window.after(250,poll);window.mainloop()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--email', help='Prefill the Gmail sender address.')
    parser.add_argument('--test', action='store_true', help='Send a delivery test after saving.')
    parser.add_argument('--gui', action='store_true', help='Open the private one-time setup window.')
    args = parser.parse_args()
    if args.gui:
        open_setup_window(args.email or 'adarsh22saji@gmail.com')
        return
    print('Enable Google 2-Step Verification and create an App Password:')
    print('https://myaccount.google.com/apppasswords')
    print('Enter the App Password here, never in chat. Do not use your normal password.')
    email = args.email or input('Sender Gmail address [adarsh22saji@gmail.com]: ').strip() or 'adarsh22saji@gmail.com'
    password = getpass.getpass('16-character Gmail App Password (hidden): ')
    try:
        path = save_configuration(email,password)
    except ValueError as error:
        raise SystemExit(str(error))
    print('Saved in .env (excluded from Git). Delivery has not been tested yet.')
    print('Restart Django, then run: python manage.py check_email --send-to ' + email)
    if args.test:
        result = subprocess.run([sys.executable, str(path.parent / 'manage.py'),
                                 'check_email', '--send-to', email], cwd=path.parent)
        if result.returncode:
            print('Delivery was not confirmed. Correct the App Password and run setup again.')
        else:
            print('Test email accepted. Return to Codex so the running app can reload these settings.')


if __name__ == '__main__':
    main()
