# Generated by Django 4.2.27 on 2026-10-02 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_legacy_message_expiry'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='register.register')),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='register.register')),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='register.register')),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversationtimer',
            constraint=models.UniqueConstraint(fields=('user_low', 'user_high'), name='unique_chat_timer'),
        ),
        migrations.AddConstraint(
            model_name='conversationtimer',
            constraint=models.CheckConstraint(check=models.Q(('user_low__lt', models.F('user_high'))), name='ordered_chat_pair'),
        ),
        migrations.AddConstraint(
            model_name='conversationtimer',
            constraint=models.CheckConstraint(check=models.Q(('duration__in', [0, 60, 86400, 604800, 7776000])), name='valid_chat_duration'),
        ),
    ]
