# Generated by Django 4.2.27 on 2026-03-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=45)),
                ('time', models.CharField(max_length=45)),
                ('photo', models.CharField(blank=True, max_length=200, null=True)),
                ('visibility', models.CharField(blank=True, max_length=45, null=True)),
                ('choose_file', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(max_length=45)),
                ('like', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('is_ghost_text', models.BooleanField(default=False)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.register')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='image.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.register')),
            ],
            options={
                'db_table': 'comment_post',
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='image.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.register')),
            ],
            options={
                'db_table': 'like_post',
                'unique_together': {('image', 'user')},
            },
        ),
    ]
