# Generated by Django 4.2.27 on 2026-10-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('follower_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'follower',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'follow_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('date_of_birth', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
                ('confirm', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
                ('reg_photo', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=15)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.IntegerField(default=0)),
                ('is_disappearing', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_messages', to='register.register')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to='register.register')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
